export type SupportedPageSmokeCase = {
  id: string;
  domain: string;
  path: `/${string}`;
  surface: 'top-level' | 'same-origin-embedded';
  selectionKind: 'word' | 'phrase' | 'sentence' | 'multi-sentence';
  input: 'pointer' | 'keyboard';
  placement: 'viewport-edge' | 'after-scroll';
  zoomPercent: 100 | 200;
  selectionText: string;
  paragraph: string;
};

export const SUPPORTED_PAGE_SMOKE_PLAN = [
  {
    id: 'site-01-article-1',
    domain: 'site-01.lingo.test',
    path: '/article-1',
    surface: 'top-level',
    selectionKind: 'word',
    input: 'pointer',
    placement: 'viewport-edge',
    zoomPercent: 100,
    selectionText: 'postpone',
    paragraph: 'The committee decided to postpone the vote until next week.',
  },
  {
    id: 'site-02-article-1',
    domain: 'site-02.lingo.test',
    path: '/article-1',
    surface: 'same-origin-embedded',
    selectionKind: 'phrase',
    input: 'pointer',
    placement: 'viewport-edge',
    zoomPercent: 100,
    selectionText: 'carry out',
    paragraph: 'The research team will carry out the field study in September.',
  },
  {
    id: 'site-03-article-1',
    domain: 'site-03.lingo.test',
    path: '/article-1',
    surface: 'top-level',
    selectionKind: 'sentence',
    input: 'keyboard',
    placement: 'viewport-edge',
    zoomPercent: 100,
    selectionText: 'The revised policy takes effect on Monday.',
    paragraph: 'The revised policy takes effect on Monday. Staff received advance notice.',
  },
  {
    id: 'site-04-article-1',
    domain: 'site-04.lingo.test',
    path: '/article-1',
    surface: 'same-origin-embedded',
    selectionKind: 'multi-sentence',
    input: 'keyboard',
    placement: 'viewport-edge',
    zoomPercent: 100,
    selectionText: 'Demand increased during spring. Production remained stable.',
    paragraph: 'Demand increased during spring. Production remained stable. The report explains why.',
  },
  {
    id: 'site-05-article-1',
    domain: 'site-05.lingo.test',
    path: '/article-1',
    surface: 'top-level',
    selectionKind: 'word',
    input: 'pointer',
    placement: 'viewport-edge',
    zoomPercent: 200,
    selectionText: 'allocate',
    paragraph: 'The council will allocate additional funds to public libraries.',
  },
  {
    id: 'site-06-article-1',
    domain: 'site-06.lingo.test',
    path: '/article-1',
    surface: 'same-origin-embedded',
    selectionKind: 'phrase',
    input: 'pointer',
    placement: 'viewport-edge',
    zoomPercent: 200,
    selectionText: 'phase out',
    paragraph: 'The manufacturer plans to phase out the older design gradually.',
  },
  {
    id: 'site-07-article-1',
    domain: 'site-07.lingo.test',
    path: '/article-1',
    surface: 'top-level',
    selectionKind: 'sentence',
    input: 'keyboard',
    placement: 'viewport-edge',
    zoomPercent: 200,
    selectionText: 'The final decision depends on the safety review.',
    paragraph: 'The final decision depends on the safety review. Results are expected soon.',
  },
  {
    id: 'site-08-article-1',
    domain: 'site-08.lingo.test',
    path: '/article-1',
    surface: 'same-origin-embedded',
    selectionKind: 'multi-sentence',
    input: 'keyboard',
    placement: 'viewport-edge',
    zoomPercent: 200,
    selectionText: 'The route crosses the valley. It then follows the northern ridge.',
    paragraph: 'The route crosses the valley. It then follows the northern ridge. Hikers should carry water.',
  },
  {
    id: 'site-09-article-1',
    domain: 'site-09.lingo.test',
    path: '/article-1',
    surface: 'top-level',
    selectionKind: 'word',
    input: 'pointer',
    placement: 'after-scroll',
    zoomPercent: 100,
    selectionText: 'retain',
    paragraph: 'The archive will retain the original records for future research.',
  },
  {
    id: 'site-10-article-1',
    domain: 'site-10.lingo.test',
    path: '/article-1',
    surface: 'same-origin-embedded',
    selectionKind: 'phrase',
    input: 'pointer',
    placement: 'after-scroll',
    zoomPercent: 100,
    selectionText: 'set aside',
    paragraph: 'The panel agreed to set aside the disputed proposal for now.',
  },
  {
    id: 'site-01-article-2',
    domain: 'site-01.lingo.test',
    path: '/article-2',
    surface: 'top-level',
    selectionKind: 'sentence',
    input: 'keyboard',
    placement: 'after-scroll',
    zoomPercent: 100,
    selectionText: 'Several neighborhoods reported lower traffic noise.',
    paragraph: 'Several neighborhoods reported lower traffic noise. The survey continues next month.',
  },
  {
    id: 'site-02-article-2',
    domain: 'site-02.lingo.test',
    path: '/article-2',
    surface: 'same-origin-embedded',
    selectionKind: 'multi-sentence',
    input: 'keyboard',
    placement: 'after-scroll',
    zoomPercent: 100,
    selectionText: 'The first trial met its target. A larger study will begin this winter.',
    paragraph: 'The first trial met its target. A larger study will begin this winter. Recruitment is open.',
  },
  {
    id: 'site-03-article-2',
    domain: 'site-03.lingo.test',
    path: '/article-2',
    surface: 'top-level',
    selectionKind: 'word',
    input: 'pointer',
    placement: 'after-scroll',
    zoomPercent: 200,
    selectionText: 'clarify',
    paragraph: 'The new diagram should clarify how the two systems interact.',
  },
  {
    id: 'site-04-article-2',
    domain: 'site-04.lingo.test',
    path: '/article-2',
    surface: 'same-origin-embedded',
    selectionKind: 'phrase',
    input: 'pointer',
    placement: 'after-scroll',
    zoomPercent: 200,
    selectionText: 'rule out',
    paragraph: 'Investigators could not rule out a temporary equipment fault.',
  },
  {
    id: 'site-05-article-2',
    domain: 'site-05.lingo.test',
    path: '/article-2',
    surface: 'top-level',
    selectionKind: 'sentence',
    input: 'keyboard',
    placement: 'after-scroll',
    zoomPercent: 200,
    selectionText: 'The updated timetable leaves more time for transfers.',
    paragraph: 'The updated timetable leaves more time for transfers. Weekend service is unchanged.',
  },
  {
    id: 'site-06-article-2',
    domain: 'site-06.lingo.test',
    path: '/article-2',
    surface: 'same-origin-embedded',
    selectionKind: 'multi-sentence',
    input: 'keyboard',
    placement: 'after-scroll',
    zoomPercent: 200,
    selectionText: 'The lake level rose overnight. Nearby trails remain closed.',
    paragraph: 'The lake level rose overnight. Nearby trails remain closed. Rangers will inspect them tomorrow.',
  },
  {
    id: 'site-07-article-2',
    domain: 'site-07.lingo.test',
    path: '/article-2',
    surface: 'top-level',
    selectionKind: 'word',
    input: 'pointer',
    placement: 'viewport-edge',
    zoomPercent: 100,
    selectionText: 'offset',
    paragraph: 'Efficiency gains may offset part of the initial construction cost.',
  },
  {
    id: 'site-08-article-2',
    domain: 'site-08.lingo.test',
    path: '/article-2',
    surface: 'same-origin-embedded',
    selectionKind: 'phrase',
    input: 'pointer',
    placement: 'viewport-edge',
    zoomPercent: 100,
    selectionText: 'draw on',
    paragraph: 'The exhibition will draw on photographs from several local archives.',
  },
  {
    id: 'site-09-article-2',
    domain: 'site-09.lingo.test',
    path: '/article-2',
    surface: 'top-level',
    selectionKind: 'sentence',
    input: 'keyboard',
    placement: 'viewport-edge',
    zoomPercent: 100,
    selectionText: 'The workshop combines practical exercises with short discussions.',
    paragraph: 'The workshop combines practical exercises with short discussions. Materials are provided.',
  },
  {
    id: 'site-10-article-2',
    domain: 'site-10.lingo.test',
    path: '/article-2',
    surface: 'same-origin-embedded',
    selectionKind: 'multi-sentence',
    input: 'keyboard',
    placement: 'viewport-edge',
    zoomPercent: 100,
    selectionText: 'Temperatures fell before dawn. Conditions improved after sunrise.',
    paragraph: 'Temperatures fell before dawn. Conditions improved after sunrise. Flights resumed at noon.',
  },
] as const satisfies readonly SupportedPageSmokeCase[];
